cellsize = [16 16]
load('data_batch_1.mat')
x_training= [];
y_training= [];
for n = 1:10000
    I = reshape(data(n,:),[32,32,3]);
    Igray = rgb2gray(I);
    feat = extractLBPFeatures(Igray, ...
                                'NumNeighbors',8, ...
                                'Radius', 1, ...
                                'Upright', true, ...
                                'Interpolation', 'Linear', ...
                                'CellSize',cellsize , ...
                                'Normalization','L2' ...
                                );
     x_training = [x_training; feat];
    
end
y_training =[y_training; labels];

load('data_batch_2.mat')
for n = 1:10000
   I = reshape(data(n,:),[32,32,3]);
   Igray = rgb2gray(I);
   feat = extractLBPFeatures(Igray, ...
                                'NumNeighbors',8, ...
                                'Radius', 1, ...
                                'Upright', true, ...
                                'Interpolation', 'Linear', ...
                                'CellSize',cellsize, ...
                                'Normalization','L2' ...
                                );
   x_training = [x_training; feat];
    
end
y_training =[y_training; labels];

load('data_batch_3.mat')
for n = 1:10000
   I = reshape(data(n,:),[32,32,3]);
   Igray = rgb2gray(I);
   feat = extractLBPFeatures(Igray, ...
                                'NumNeighbors',8, ...
                                'Radius', 1, ...
                                'Upright', true, ...
                                'Interpolation', 'Linear', ...
                                'CellSize',cellsize, ...
                                'Normalization','L2' ...
                                );
    x_training = [x_training; feat];
    
end
y_training =[y_training; labels];

load('data_batch_4.mat')
for n = 1:10000
   I = reshape(data(n,:),[32,32,3]);
   Igray = rgb2gray(I);
   feat = extractLBPFeatures(Igray, ...
                                'NumNeighbors',8, ...
                                'Radius', 1, ...
                                'Upright', true, ...
                                'Interpolation', 'Linear', ...
                                'CellSize',cellsize, ...
                                'Normalization','L2' ...
                                );
   x_training = [x_training; feat];  
end
y_training =[y_training; labels];

load('data_batch_5.mat')
for n = 1:10000
   I = reshape(data(n,:),[32,32,3]);
   Igray = rgb2gray(I);
   feat = extractLBPFeatures(Igray, ...
                                'NumNeighbors',8, ...
                                'Radius', 1, ...
                                'Upright', true, ...
                                'Interpolation', 'Linear', ...
                                'CellSize', cellsize, ...
                                'Normalization','L2' ...
                                );
    x_training = [x_training; feat];  
    
end
y_training =[y_training; labels];

load('test_batch.mat')
x_test = [];
y_test = []
for n = 1:10000
   I = reshape(data(n,:),[32,32,3]);
   Igray = rgb2gray(I);
   feat = extractLBPFeatures(Igray, ...
                                'NumNeighbors',8, ...
                                'Radius', 1, ...
                                'Upright', true, ...
                                'Interpolation', 'Linear', ...
                                'CellSize', cellsize, ...
                                'Normalization','L2' ...
                                );
   x_test = [x_test; feat];
end
y_test = labels;
save('training_test_16.mat', 'x_training', 'y_training', 'x_test', 'y_test')